version: '3.3'
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./conf/nginx/api.conf:/etc/nginx/conf.d/api.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_API}"

  web:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./conf/nginx/web.conf:/etc/nginx/conf.d/api.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_WEB}"

  php:
    image: lcidral/php:7.2.6-fpm-xdebug-alpine
    restart: always
    depends_on:
      - reverse-proxy
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./:/var/www/html
      - ./conf/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf/php/docker-php-ext-sendmail.ini:/usr/local/etc/php/conf.d/docker-php-ext-sendmail.ini
      - ./conf/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    env_file:
      - ./conf/docker/environment.config

  php56:
    image: php:5.6-fpm
    working_dir: "/var/www"
    restart: always
    depends_on:
      - reverse-proxy
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./public/web56:/var/www
      - ./conf/php/php56.ini:/usr/local/etc/php/conf.d/php.ini:ro
    env_file:
      - ./conf/docker/environment.config

  web56:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php56
    volumes:
      - ./conf/nginx/web56.conf:/etc/nginx/conf.d/web.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_WEB56}"

  mariadb:
    image: mariadb:10.1.26
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      VIRTUAL_HOST: '${DB_HOST}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  mail:
    image: lcidral/mailcatcher.dev:latest
    ports:
      - '1025:1025'
      - '1080:1080'

  selenium-hub:
    image: selenium/hub:3.12.0-boron
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:3.12.0-boron
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
        - 5900:5900
    volumes:
        - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox-debug:3.12.0-boron
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
        - 5901:5900
    volumes:
        - /dev/shm:/dev/shm
