version: '3.3'
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./conf/nginx/api.conf:/etc/nginx/conf.d/api.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_API}"

  bot:
    image: nginx:1.13.3-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./conf/nginx/bot.conf:/etc/nginx/conf.d/bot.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_BOT}"

  www:
    image: nginx:1.13.3-alpine
    restart: always
    hostname: "www"
    depends_on:
      - php
    volumes:
      - ./conf/nginx/www.conf:/etc/nginx/conf.d/www.conf:rw
      - ./logs:/var/log/nginx
    labels:
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_WWW}"

  php:
    image: lcidral/php:7.2.9-fpm-xdebug-alpine
    restart: always
    depends_on:
      - reverse-proxy
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./:/var/www/html
      - ./public/images:/var/www/html/public/images
      - ./conf/php/7.2/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./conf/php/7.2/docker-php-ext-sendmail.ini:/usr/local/etc/php/conf.d/docker-php-ext-sendmail.ini
      - ./conf/php/7.2/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    env_file:
      - .env

  mariadb:
    image: mariadb:10.1.26
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      VIRTUAL_HOST: "${DB_HOST}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  redis:
    image: redis
    ports:
      - "6379"
    volumes:
      - "./storage/redis:/data"

  mail:
    image: lcidral/mailcatcher.dev:latest
    ports:
      - "1025:1025"
      - "1080:1080"

  selenium-hub:
    image: selenium/hub:3.12.0-boron
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:3.12.0-boron
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox-debug:3.12.0-boron
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5901:5900
    volumes:
      - /dev/shm:/dev/shm

  mongo:
    image: mongo:3.2
    hostname: "mongo"
    volumes:
      - mongodb_data:/data/db
      - mongodb_dump:/dump
    command: mongod --smallfiles --oplogSize 128
    logging:
      options:
        max-size: 10m
        max-file: '3'

  rocketchat:
    image: rocket.chat:latest
    hostname: "rocketchat"
    depends_on:
      - mongo
    volumes:
      - rocketchat_uploads:/app/uploads
    environment:
      - PORT=3000
      - "ROOT_URL=http://${ROCKETCHAT_URL}:3000"
      - MONGO_URL=mongodb://mongo:27017/rocketchat
    links:
      - mongo:mongo
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST_ROCKETCHAT}"
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  rocketchat_uploads:
  mongodb_data:
  mongodb_dump:
  mariadb_data: